export const writing = /*html*/ `
  <svg width="800" height="1000" viewBox="0 0 800 1000" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect width="800" height="1000" fill="white"/>
  <text fill="black" xml:space="preserve" style="white-space: pre" font-family="Arial" font-size="16" letter-spacing="0em"><tspan x="100" y="703.484">One of the principles of durable typography is always legibility; another is something </tspan><tspan x="100" y="729.084">more than legibility: some earned or unearned interest that gives its living energy to </tspan><tspan x="100" y="754.684">the page. It takes various forms and goes by various names, including serenity, </tspan><tspan x="100" y="780.284">liveliness, laughter, grace and joy</tspan></text>
  <text fill="black" xml:space="preserve" style="white-space: pre" font-family="Arial" font-size="20" letter-spacing="0em"><tspan x="100" y="663.105">Durable Typography</tspan></text>
  <text fill="black" xml:space="preserve" style="white-space: pre" font-family="Arial" font-size="14" letter-spacing="0em"><tspan x="100" y="820.674">&#x2014; Legibility</tspan></text>
  <text fill="black" xml:space="preserve" style="white-space: pre" font-family="Arial" font-size="43.9953" letter-spacing="-0.04em"><tspan x="100" y="172.828">Typography exists to honor </tspan><tspan x="100" y="221.223">content</tspan></text>
  <text fill="black" xml:space="preserve" style="white-space: pre" font-family="Arial" font-size="18.5" letter-spacing="0em"><tspan x="100" y="270.748">Like oratory, music, dance, calligraphy - like anything that lends its grace </tspan><tspan x="100" y="296.648">to language - typography is an art that can be deliberately misused. It is </tspan><tspan x="100" y="322.548">a craft by which the meanings of a text (or its absence of meaning) can </tspan><tspan x="100" y="348.448">be clarified, honored and shared, or knowingly disguised. </tspan></text>
  <text fill="black" xml:space="preserve" style="white-space: pre" font-family="Arial" font-size="16" letter-spacing="0em"><tspan x="100" y="121.484">First Principles</tspan></text>
  <text fill="black" xml:space="preserve" style="white-space: pre" font-family="Arial" font-size="16" letter-spacing="0em"><tspan x="100" y="396.484">In a world rife with unsolicited messages, typography must often draw attention to </tspan><tspan x="100" y="422.084">itself before it will be read. Yet in order to be read, it must relinquish the attention it </tspan><tspan x="100" y="447.684">has drawn. Typography with anything to say therefore aspires to a kind of </tspan><tspan x="100" y="473.284">statuesque transparency. Its other traditional goal is durability: not immunity to </tspan><tspan x="100" y="498.884">change, but a clear superiority to fashion.</tspan></text>
  <text fill="black" xml:space="preserve" style="white-space: pre" font-family="Arial" font-size="22" font-style="italic" font-weight="bold" letter-spacing="0em"><tspan x="100" y="554.916">Typography at its best is a visual form of language </tspan><tspan x="100" y="585.716">linking timelessness and time. </tspan></text>
  <text fill="black" xml:space="preserve" style="white-space: pre" font-family="Arial" font-size="14" letter-spacing="0em"><tspan x="100" y="851.674">&#x2014;  Interest</tspan></text>
  <text fill="black" xml:space="preserve" style="white-space: pre" font-family="Arial" font-size="14" letter-spacing="0em"><tspan x="100" y="882.674">&#x2014;  Liveliness</tspan></text>
  </svg>
`;
